import os
from dotenv import load_dotenv

load_dotenv()

class Config:
    """Flask configuration settings."""
    SECRET_KEY = os.environ.get('SECRET_KEY') or 'you-will-never-guess'
    TMDB_API_KEY = os.environ.get('TMDB_API_KEY')
    TMDB_BASE_URL = 'https://api.themoviedb.org/3'
    TMDB_IMAGE_BASE_URL = 'https://image.tmdb.org/t/p'
    DEFAULT_LANGUAGE = 'en-US'
    
    # Available languages
    LANGUAGES = {
        'en': 'English',
        'ro': 'Română',
        'es': 'Español',
        'fr': 'Français',
        'de': 'Deutsch'
    }
    
    LANGUAGE_FLAGS = {
        'en': '🇺🇸',
        'ro': '🇷🇴',
        'es': '🇪🇸',
        'fr': '🇫🇷',
        'de': '🇩🇪'
    }
    
    # Translations for UI elements
    TRANSLATIONS = {
        'en': {
            'home': 'Home',
            'movies': 'Movies',
            'tv': 'TV Shows',
            'watchlist': 'Watchlist',
            'featured': 'Featured',
            'watchNow': 'Watch Now',
            'addToWatchlist': 'Add to Watchlist',
            'trendingNow': 'Trending Now',
            'popularMovies': 'Popular Movies',
            'popularTVShows': 'Popular TV Shows',
            'topRated': 'Top Rated',
            'browseByGenre': 'Browse by Genre',
            'seeAll': 'See All',
            'inWatchlist': 'In Watchlist',
            'addedToWatchlist': 'Added to watchlist',
            'removedFromWatchlist': 'Removed from watchlist',
            'cast': 'Cast',
            'playTrailer': 'Play Trailer',
            'noOverview': 'No overview available',
            'noTrailer': 'No trailer available',
            'footerText': 'Your ultimate destination for discovering movies and TV shows from around the world.',
            'browse': 'Browse',
            'company': 'Company',
            'aboutUs': 'About Us',
            'contact': 'Contact',
            'careers': 'Careers',
            'support': 'Support',
            'helpCenter': 'Help Center',
            'termsOfService': 'Terms of Service',
            'privacyPolicy': 'Privacy Policy',
            'copyright': '© 2024 CineStream Pro. All rights reserved.',
            'poweredBy': 'Powered by',
            'followUs': 'Follow Us',
            'tvShows': 'TV Shows',
            'allGenres': 'All Genres',
            'allYears': 'All Years',
            'sortBy': 'Sort By',
            'popularity': 'Popularity',
            'rating': 'Rating',
            'releaseDate': 'Release Date',
            'reset': 'Reset',
            'loadMore': 'Load More',
            'savedContent': 'Your saved movies and TV shows',
            'totalItems': 'Total Items',
            'emptyWatchlist': 'Your watchlist is empty',
            'emptyWatchlistDesc': 'Start adding movies and TV shows to your list to watch later.',
            'browseMovies': 'Browse Movies',
            'voteCount': 'Vote Count',
            'revenue': 'Revenue',
            'noResults': 'No results found',
            'moviesAvailable': 'Movies Available',
            'activeUsers': 'Active Users',
            'countries': 'Countries'
        },
        'ro': {
            'home': 'Acasă',
            'movies': 'Filme',
            'tv': 'Seriale TV',
            'watchlist': 'Listă',
            'featured': 'Recomandat',
            'watchNow': 'Vizionează Acum',
            'addToWatchlist': 'Adaugă la Listă',
            'trendingNow': 'În Tendințe',
            'popularMovies': 'Filme Populare',
            'popularTVShows': 'Seriale TV Populare',
            'topRated': 'Top Evaluări',
            'browseByGenre': 'Navighează după Gen',
            'seeAll': 'Vezi Tot',
            'inWatchlist': 'În Listă',
            'addedToWatchlist': 'Adăugat la listă',
            'removedFromWatchlist': 'Eliminat din listă',
            'cast': 'Distribuție',
            'playTrailer': 'Rulează Trailerul',
            'noOverview': 'Nu există descriere',
            'noTrailer': 'Nu există trailer disponibil',
            'footerText': 'Destinația ta ultimă pentru descoperirea filmelor și serialelor TV din întreaga lume.',
            'browse': 'Navighează',
            'company': 'Companie',
            'aboutUs': 'Despre Noi',
            'contact': 'Contact',
            'careers': 'Cariere',
            'support': 'Suport',
            'helpCenter': 'Centru Ajutor',
            'termsOfService': 'Termeni de Servicii',
            'privacyPolicy': 'Politica de Confidențialitate',
            'copyright': '© 2024 CineStream Pro. Toate drepturile rezervate.',
            'poweredBy': 'Powered by',
            'followUs': 'Urmărește-ne',
            'tvShows': 'Seriale TV',
            'allGenres': 'Toate Genurile',
            'allYears': 'Toți Anii',
            'sortBy': 'Sortează după',
            'popularity': 'Popularitate',
            'rating': 'Evaluare',
            'releaseDate': 'Data Lansării',
            'reset': 'Resetează',
            'loadMore': 'Încarcă Mai Multe',
            'savedContent': 'Filmele și serialele tale salvate',
            'totalItems': 'Total Elemente',
            'emptyWatchlist': 'Lista ta este goală',
            'emptyWatchlistDesc': 'Începe să adaugi filme și seriale TV în lista ta pentru a le viziona mai târziu.',
            'browseMovies': 'Răsfoiește Filme',
            'voteCount': 'Număr Voturi',
            'revenue': 'Venituri',
            'noResults': 'Nu s-au găsit rezultate',
            'moviesAvailable': 'Filme Disponibile',
            'activeUsers': 'Utilizatori Activi',
            'countries': 'Țări'
        },
        'es': {
            'home': 'Inicio',
            'movies': 'Películas',
            'tv': 'Series TV',
            'watchlist': 'Lista',
            'featured': 'Destacado',
            'watchNow': 'Ver Ahora',
            'addToWatchlist': 'Añadir a Lista',
            'trendingNow': 'Tendencias',
            'popularMovies': 'Películas Populares',
            'popularTVShows': 'Series TV Populares',
            'topRated': 'Mejor Valoradas',
            'browseByGenre': 'Explorar por Género',
            'seeAll': 'Ver Todo',
            'inWatchlist': 'En Lista',
            'addedToWatchlist': 'Añadido a la lista',
            'removedFromWatchlist': 'Eliminado de la lista',
            'cast': 'Reparto',
            'playTrailer': 'Ver Tráiler',
            'noOverview': 'Sin descripción disponible',
            'noTrailer': 'No hay tráiler disponible',
            'footerText': 'Tu destino definitivo para descubrir películas y series TV de todo el mundo.',
            'browse': 'Explorar',
            'company': 'Empresa',
            'aboutUs': 'Sobre Nosotros',
            'contact': 'Contacto',
            'careers': 'Empleo',
            'support': 'Soporte',
            'helpCenter': 'Centro de Ayuda',
            'termsOfService': 'Términos de Servicio',
            'privacyPolicy': 'Política de Privacidad',
            'copyright': '© 2024 CineStream Pro. Todos los derechos reservados.',
            'poweredBy': 'Desarrollado por',
            'followUs': 'Síguenos',
            'tvShows': 'Series TV',
            'allGenres': 'Todos los Géneros',
            'allYears': 'Todos los Años',
            'sortBy': 'Ordenar Por',
            'popularity': 'Popularidad',
            'rating': 'Calificación',
            'releaseDate': 'Fecha de Estreno',
            'reset': 'Restablecer',
            'loadMore': 'Cargar Más',
            'savedContent': 'Tus películas y series guardadas',
            'totalItems': 'Total de Elementos',
            'emptyWatchlist': 'Tu lista está vacía',
            'emptyWatchlistDesc': 'Comienza a añadir películas y series a tu lista para verlas después.',
            'browseMovies': 'Explorar Películas',
            'voteCount': 'Número de Votos',
            'revenue': 'Ingresos',
            'noResults': 'No se encontraron resultados',
            'moviesAvailable': 'Películas Disponibles',
            'activeUsers': 'Usuarios Activos',
            'countries': 'Países'
        },
        'fr': {
            'home': 'Accueil',
            'movies': 'Films',
            'tv': 'Séries TV',
            'watchlist': 'Liste',
            'featured': 'À la Une',
            'watchNow': 'Regarder',
            'addToWatchlist': 'Ajouter à la Liste',
            'trendingNow': 'Tendances',
            'popularMovies': 'Films Populaires',
            'popularTVShows': 'Séries TV Populaires',
            'topRated': 'Mieux Notés',
            'browseByGenre': 'Explorer par Genre',
            'seeAll': 'Voir Tout',
            'inWatchlist': 'Dans la Liste',
            'addedToWatchlist': 'Ajouté à la liste',
            'removedFromWatchlist': 'Retiré de la liste',
            'cast': 'Distribution',
            'playTrailer': 'Voir la Bande-annonce',
            'noOverview': 'Aucune description disponible',
            'noTrailer': 'Aucune bande-annonce disponible',
            'footerText': 'Votre destination ultime pour découvrir des films et séries TV du monde entier.',
            'browse': 'Explorer',
            'company': 'Entreprise',
            'aboutUs': 'À Propos',
            'contact': 'Contact',
            'careers': 'Carrières',
            'support': 'Support',
            'helpCenter': 'Centre d\'Aide',
            'termsOfService': 'Conditions d\'Utilisation',
            'privacyPolicy': 'Politique de Confidentialité',
            'copyright': '© 2024 CineStream Pro. Tous droits réservés.',
            'poweredBy': 'Propulsé par',
            'followUs': 'Suivez-nous',
            'tvShows': 'Séries TV',
            'allGenres': 'Tous les Genres',
            'allYears': 'Toutes les Années',
            'sortBy': 'Trier Par',
            'popularity': 'Popularité',
            'rating': 'Note',
            'releaseDate': 'Date de Sortie',
            'reset': 'Réinitialiser',
            'loadMore': 'Charger Plus',
            'savedContent': 'Vos films et séries enregistrés',
            'totalItems': 'Total des Éléments',
            'emptyWatchlist': 'Votre liste est vide',
            'emptyWatchlistDesc': 'Commencez à ajouter des films et séries à votre liste pour les regarder plus tard.',
            'browseMovies': 'Explorer les Films',
            'voteCount': 'Nombre de Votes',
            'revenue': 'Recettes',
            'noResults': 'Aucun résultat trouvé',
            'moviesAvailable': 'Films Disponibles',
            'activeUsers': 'Utilisateurs Actifs',
            'countries': 'Pays'
        },
        'de': {
            'home': 'Startseite',
            'movies': 'Filme',
            'tv': 'Serien',
            'watchlist': 'Liste',
            'featured': 'Empfohlen',
            'watchNow': 'Jetzt Ansehen',
            'addToWatchlist': 'Zur Liste Hinzufügen',
            'trendingNow': 'Im Trend',
            'popularMovies': 'Beliebte Filme',
            'popularTVShows': 'Beliebte Serien',
            'topRated': 'Bestbewertet',
            'browseByGenre': 'Nach Genre Durchsuchen',
            'seeAll': 'Alle Anzeigen',
            'inWatchlist': 'In der Liste',
            'addedToWatchlist': 'Zur Liste hinzugefügt',
            'removedFromWatchlist': 'Von der Liste entfernt',
            'cast': 'Besetzung',
            'playTrailer': 'Trailer Ansehen',
            'noOverview': 'Keine Beschreibung verfügbar',
            'noTrailer': 'Kein Trailer verfügbar',
            'footerText': 'Ihre ultimative Destination für die Entdeckung von Filmen und Serien aus aller Welt.',
            'browse': 'Durchsuchen',
            'company': 'Unternehmen',
            'aboutUs': 'Über Uns',
            'contact': 'Kontakt',
            'careers': 'Karriere',
            'support': 'Support',
            'helpCenter': 'Hilfezentrum',
            'termsOfService': 'Nutzungsbedingungen',
            'privacyPolicy': 'Datenschutzrichtlinie',
            'copyright': '© 2024 CineStream Pro. Alle Rechte vorbehalten.',
            'poweredBy': 'Unterstützt von',
            'followUs': 'Folgen Sie uns',
            'tvShows': 'Serien',
            'allGenres': 'Alle Genres',
            'allYears': 'Alle Jahre',
            'sortBy': 'Sortieren Nach',
            'popularity': 'Beliebtheit',
            'rating': 'Bewertung',
            'releaseDate': 'Erscheinungsdatum',
            'reset': 'Zurücksetzen',
            'loadMore': 'Mehr Laden',
            'savedContent': 'Ihre gespeicherten Filme und Serien',
            'totalItems': 'Gesamtelemente',
            'emptyWatchlist': 'Ihre Watchlist ist leer',
            'emptyWatchlistDesc': 'Beginnen Sie damit, Filme und Serien zu Ihrer Liste hinzuzufügen, um sie später anzusehen.',
            'browseMovies': 'Filme Durchsuchen',
            'voteCount': 'Anzahl der Stimmen',
            'revenue': 'Einnahmen',
            'noResults': 'Keine Ergebnisse gefunden',
            'moviesAvailable': 'Filme Verfügbar',
            'activeUsers': 'Aktive Nutzer',
            'countries': 'Länder'
        }
    }
